const funfacts = [
  "EVERYONE HAS A UNIQUE SMELL, EXCEPT IDENTICAL TWINS – THEY SMELL THE SAME!",
  "A HUMAN FETUS ACQUIRES FINGERPRINTS AT THE AGE OF THREE MONTHS. YOU ARE UNIQUE FROM THE VERY START.",
  "EVERY INDIVIDUAL HAS A UNIQUE TONGUE PRINT. LIKE FINGERPRINTS, YOUR TONGUE PRINT CAN BE USED TO IDENTIFY YOU.",
  "THE FASTEST GROWING NAIL IS ON THE MIDDLE FINGER... YES, THAT MIDDLE FINGER.",
  "ON AVERAGE, PEOPLE WHO DREAM MORE OFTEN AND MORE VIVIDLY HAVE HIGHER I.QS. SLEEP TIGHT AND DREAM.",
  "SNEEZES REGULARLY EXCEED 100 MPH, WHILE COUGHS CLOCK IN AT ABOUT 60 MPH. TROPICAL STORM FORCE WINDS STRAIGHT FROM YOUR BODY!",
  "IT IS NOT POSSIBLE TO TICKLE YOURSELF. WHEN YOU TRY YOU ARE AWARE OF THE EXACT TIME AND MANNER IN WHICH THE TICKLING WILL OCCUR, UNLIKE WHEN SOMEONE ELSE TICKLE...",
  "YOUR NOSE IS NOT AS SENSITIVE AS A DOG'S, BUT IT CAN REMEMBER 50,000 DIFFERENT SCENTS. CHOCOLATE CHIP COOKIES TRANSPORTING YOU TO GRAMMA’S KITCHEN IS ALWAYS A F...",
  "YOUR PET ISN'T THE ONLY ONE IN THE HOUSE WITH A SHEDDING PROBLEM. HUMANS SHED ABOUT 600,000 PARTICLES OF SKIN EVERY HOUR, OR 1.5 POUNDS EACH YEAR. ON AVERAGE PE...",
  "AROUND HALF OF ALL TEEN-AGERS ARE SLEEP-DEPRIVED. DESPITE WHAT PARENTS MIGHT THINK, MANY TEENS ARE LACKING IN ZZZZS.",
  "WE SPEND ABOUT 10% OF OUR WAKING HOURS WITH OUR EYES CLOSED, BLINKING. THAT’S 10-20 TIMES PER MINUTE",
  "YOUR HEARTBEAT CHANGES AND MIMICS THE MUSIC YOU LISTEN TO. MUSIC SLOWS YOU DOWN OR REVS YOU UP DEPENDING UPON THE TEMPO.",
  "ATHAZAGORAPHOBIA IS THE FEAR OF BEING IGNORED OR FORGOTTEN. TRY PRONOUNCING IT!",
  "BEARDS ARE THE FASTEST GROWING HAIRS ON THE HUMAN BODY. IF THE AVERAGE MAN NEVER TRIMMED HIS BEARD, IT WOULD GROW TO NEARLY 30 FEET LONG IN HIS LIFETIME.",
];

export default funfacts;
